name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-tests:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ "16.x", "18.x" ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Backend Dependencies
        run: npm install
        working-directory: backend
      - name: Run Backend Tests
        run: npm test
        working-directory: backend

  website-build:
    name: Build Astro Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install Website Dependencies
        run: npm install
        working-directory: public-directory-website
      - name: Build Website
        run: npm run build
        working-directory: public-directory-website
